### ISSUE TITLE
Improve Error Message for Invalid Password in `PlatformUserModel.create_user` method

### ISSUE THREAD

**Issue by shahharsh176** [Healthlane-Technologies/zelthy3#174]
### Description

Currently, the error message displayed for invalid password supplied to the [`PlatformUserModel.create_user`](https://github.com/Healthlane-Technologies/zelthy3/blob/main/backend/src/zelthy/apps/shared/platformauth/models.py#L80) method is not user-friendly.

### Background

The current error message is difficult for users to understand.

### Feature Details

When an invalid password is supplied to the [`PlatformUserModel.create_user`](https://github.com/Healthlane-Technologies/zelthy3/blob/main/backend/src/zelthy/apps/shared/platformauth/models.py#L80)  method, the following error message should be raised:

```text
Invalid Password

The password provided does not meet the required criteria. Please ensure that your password follows these rules:
1. Must contain at least 8 characters.
2. Must contain at least one uppercase letter.
3. Must contain at least one lowercase letter.
4. Must contain at least one number.
5. Must contain at least one special character.

```

**Comment by AjaySDwivedi1** [comment]
I can work on this.

**Comment by shahharsh176** [comment]
> I can work on this.

Sure @AjaySDwivedi1 . Please go ahead.

**Comment by AjaySDwivedi1** [comment]
I created a pull request. Let me know if I need to fix anything or if the code is wrong.

**Comment by shahharsh176** [comment]
@AjaySDwivedi1 I have requested some changes in the PR

**Comment by AjaySDwivedi1** [comment]
> @AjaySDwivedi1 I have requested some changes in the PR

Sorry that was an accidental delete. I added it back. Let me know if that works.
